CC = gcc
CFLAGS = -Wall -Werror -g

EXECS = \
	exo3_un_process \
	exo3_plusieurs_process \

all : $(EXECS)

exo3_un_process: exo3_un_process.o matrice.o traiterLigne.o
	$(CC) -o $@ $^ $(CFLAGS)

exo3_plusieurs_process: exo3_plusieurs_process.o matrice.o traiterLigne.o
		$(CC) -o $@ $^ $(CFLAGS)

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)
