SELECT table_name FROM ALL_TABLES
WHERE OWNER='GILLES_HUBERT' and table_name like 'TP3_%';

SELECT COLUMN_NAME, TABLE_NAME FROM ALL_TAB_COLUMNS
WHERE OWNER='GILLES_HUBERT' and table_name like 'TP3_%';

SELECT * FROM ALL_CONSTRAINTS
WHERE OWNER='GILLES_HUBERT' and table_name like 'TP3_%' and CONSTRAINT_TYPE='R';

SELECT * FROM SYS.ALL_CONS_COLUMNS
WHERE OWNER='GILLES_HUBERT' and table_name like 'TP3_%';